version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Mg8Kp2Nx9Wd5Qz7Bh3Rf6
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - mongo-express
      - cloudbeaver
      - tesi-blazor
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=f>M6;AhC8?\\r(5AdfHdy=+Z
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Mg8Kp2Nx9Wd5Qz7Bh3Rf6
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
      - ME_CONFIG_SITE_BASEURL=/mongo/
      - ME_CONFIG_MONGODB_URL=mongodb://admin:Mg8Kp2Nx9Wd5Qz7Bh3Rf6@mongodb:27017/
    depends_on:
      - mongodb
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8082:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    environment:
      - CB_ADMIN_NAME=admin
      - CB_ADMIN_PASSWORD=password123
    depends_on:
      - sqlserver
    restart: unless-stopped

  tesi-blazor:
    build:
      context: ./tesi
      dockerfile: Dockerfile.published
    ports:
      - "8083:8083"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongodb
      - sqlserver
    restart: unless-stopped

volumes:
  sqlserver_data:
  mongodb_data:
  cloudbeaver_data:
